"""
Freshdesk Ticket Creation Script

DESCRIPTION:
This script creates support tickets in the Freshdesk helpdesk system.
Freshdesk is a cloud-based customer support platform that helps businesses
manage customer inquiries, support requests, and service tickets through a
unified interface.

REQUIREMENTS:
- Python 3.x
- requests library (install with: pip install requests)
- Valid Freshdesk API key with ticket creation permissions
- Freshdesk account and domain access

SETUP INSTRUCTIONS:
1. Replace API_KEY with your actual Freshdesk API key
2. Replace DOMAIN with your Freshdesk domain (e.g., 'yourcompany.freshdesk.com')
3. Ensure your API key has the necessary permissions for ticket creation
4. Run the script: python create_ticket.py

API DOCUMENTATION:
- Freshdesk API v2: https://developers.freshdesk.com/api/
- Authentication: Basic Auth with API key
- Rate Limits: 50 requests per minute for most endpoints

INPUT PARAMETERS:
- subject: Brief title for the ticket (required)
- description: Detailed description of the issue (required)
- status: Ticket status (2 = Open, 3 = Pending, 4 = Resolved, 5 = Closed)
- priority: Priority level (1 = Low, 2 = Medium, 3 = High, 4 = Urgent)
- group_id: ID of the group to assign the ticket to
- responder_id: ID of the specific agent to assign the ticket to
- email: Email address of the requester

OUTPUT:
- Creates 8 sample tickets with random subjects and descriptions
- Prints ticket creation status and IDs to console
- Handles rate limiting automatically with retry logic

ERROR HANDLING:
- Checks for HTTP 429 (rate limit exceeded) and retries after delay
- Displays error messages for failed requests
- Includes 1-second delay between requests to avoid rate limits

MODIFICATION OPTIONS:
- Change the number of tickets created (line 74: range(8))
- Modify sample subjects/descriptions in TICKET_SUBJECTS/TICKET_DESCRIPTIONS
- Update default status, priority, group_id, responder_id as needed
- Add custom fields by including them in the payload dictionary

SECURITY NOTE:
- Store API keys securely (environment variables recommended for production)
- Never commit API keys to version control
- Rotate API keys regularly for security

TROUBLESHOOTING:
- Verify API key has ticket creation permissions
- Check Freshdesk domain is correct
- Ensure network connectivity to Freshdesk API
- Monitor rate limit usage in Freshdesk dashboard
"""

import requests
import json
import time
import random
import os

# Freshdesk API Configuration
# TODO: Move these to environment variables for security
API_KEY = "5TMgbcZdRFY70hSpEdj"  # Replace with your actual API key
DOMAIN = "benchmarkeducationcompany.freshdesk.com"  # Replace with your domain
API_URL = f"https://{DOMAIN}/api/v2/tickets"

# HTTP Headers for API requests
HEADERS = {
    "Content-Type": "application/json"
}

# Sample ticket subjects and descriptions for testing purposes
# These are example subjects related to subscription and email issues
TICKET_SUBJECTS = [
    "Subscription issue with Celigo",
    "Duplicate email problem detected",
    "Request for subscription hold verification",
    "Automated email conflicts",
    "Issue with old vs new process",
    "Support needed for duplicate emails",
    "Celigo fulfillment delay",
    "Unexpected email generation error"
]

# Corresponding descriptions that match the subjects above
# Each description provides context for the support issue
TICKET_DESCRIPTIONS = [
    "The user has received duplicate emails for their subscription. Please verify and resolve.",
    "A subscription fulfillment email was generated by Celigo, but the new process already sent it.",
    "Check why the system is still sending old-style subscription emails.",
    "New automated process conflicts with Celigo email sending.",
    "Customer reports receiving duplicate subscription confirmation emails.",
    "An agent needs help identifying duplicate subscription issues.",
    "Email fulfillment process seems to be delayed due to old processing system.",
    "Customer received an email from Celigo that should have been suppressed."
]

def generate_random_email():
    """
    Generate a random email address for testing purposes.

    This function creates fake email addresses using common first names,
    last names, and random numbers. These are NOT real email addresses
    and should only be used for testing.

    Returns:
        str: A randomly generated email address in format 'firstname.lastname123@example.com'
    """
    first_names = ["john", "jane", "alex", "chris", "mike", "sarah", "emma", "ryan"]
    last_names = ["smith", "doe", "johnson", "brown", "davis", "wilson", "taylor", "martin"]
    domain = "example.com"

    # Create email in format: firstname.lastname123@example.com
    return f"{random.choice(first_names)}.{random.choice(last_names)}{random.randint(100,999)}@{domain}"

def create_ticket(subject, description):
    """
    Create a single support ticket in Freshdesk.

    This function sends a POST request to the Freshdesk API to create
    a new ticket with the specified subject and description.

    Args:
        subject (str): The ticket title/subject line
        description (str): Detailed description of the issue

    Returns:
        None: Prints success/failure messages to console

    Note:
        - Automatically assigns to group ID 67000578451 ('Old Subs' group)
        - Assigns to specific agent (responder_id: 67051499418)
        - Sets status to Open (2) and priority to Low (1)
        - Uses random email for requester (for testing)
    """
    # Prepare the ticket data payload
    payload = {
        "subject": subject,
        "description": description,
        "status": 2,  # 2 = Open status
        "priority": 1,  # 1 = Low priority
        "group_id": 67000578451,  # Assign to 'Old Subs' group
        "responder_id": 67051499418,  # Assign to specific agent
        "email": generate_random_email()  # Random requester email for testing
    }

    # Make the API request to create the ticket
    response = requests.post(API_URL, auth=(API_KEY, "X"), headers=HEADERS, data=json.dumps(payload))

    # Handle API rate limiting (HTTP 429)
    if response.status_code == 429:
        # Get retry delay from response headers (default to 5 seconds)
        retry_after = int(response.headers.get("Retry-After", 5))
        print(f"Rate limit exceeded. Retrying in {retry_after} seconds...")
        time.sleep(retry_after)
        # Retry the request recursively
        return create_ticket(subject, description)

    # Check if ticket was created successfully
    if response.status_code == 201:
        # Extract the new ticket ID from the response
        ticket_id = response.json().get("id")
        print(f"✓ Ticket created successfully: ID {ticket_id}")
        print(f"  Subject: {subject}")
        print(f"  Status: Created and assigned to group")
    else:
        # Display error information if creation failed
        print(f"✗ Failed to create ticket: {response.status_code}")
        print(f"  Error: {response.text}")
        print(f"  Subject: {subject}")

def main():
    """
    Main function to create multiple test tickets.

    This function creates 8 sample tickets using random combinations
    of subjects and descriptions. Includes delays to respect API rate limits.
    """
    print("Starting ticket creation process...")
    print("=" * 50)

    # Create 8 tickets with random subject/description combinations
    for ticket_num in range(8):
        print(f"\nCreating ticket #{ticket_num + 1}...")

        # Select random subject and description
        subject = random.choice(TICKET_SUBJECTS)
        description = random.choice(TICKET_DESCRIPTIONS)

        # Create the ticket
        create_ticket(subject, description)

        # Wait 1 second between requests to avoid rate limits
        if ticket_num < 7:  # Don't wait after the last ticket
            print("Waiting 1 second before next ticket...")
            time.sleep(1)

    print("\n" + "=" * 50)
    print("Ticket creation process completed!")

# Run the script if executed directly
if __name__ == "__main__":
    main()

